# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e36baa347d2e0070ca8517e87614bb058ed2015e1169486bca05e5166d977716d1b8903055efe156713f8113d7db600ad627dafa5df8c840c3ad8bc01f181a1b

test:
  secret_key_base: d961013af13354476fcc00d8e509ecea52fb122433a87dd11c50addcbbae85652d64dc4cd2d34b6f565bf18909f125e6cc8693e60973d1f93bd7bbf2bcf59c7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
